---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.74.3_Linux-64bit.deb
  - rm -rf public/
  - hugo env
before_script: git lfs pull
script:
  - HUGO_ENV=production hugo --gc --minify -v
  - cp CNAME public/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: thomasantony/thomasantony.github.io
  target_branch: master
  on:
    branch: master
