baseurl = "https://www.thomasantony.com/"
title = "Thomas Antony"
# author = "Thomas Antony"
canonifyurls = true
languagecode = "en"
googleAnalytics = "UA-56045487-1"
defaultContentLanguage = "en"


theme = "KeepIt"

[params]
author = "Thomas Antony"
subtitle = "A blog"
home_mode = "other" # post or other

google_verification = ""
bing_verification = ""
yandex_verification = ""
pinterest_verification = ""
baidu_verification = ""

avatar = "/images/me/avatar.jpeg"
socialShare = true

description = "" # site description
keywords = "" # site keywords

license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

paginate = 12
enableEmoji = true
enableRobotsTXT = true

[params.social]
    GitHub = "thomasantony"
    Linkedin = "thomasantony"
    Twitter = "thomasantony"

[params.share]
Twitter = true
Facebook = true
Linkedin = true

 
[Permalinks]
    posts = "/:year/:filename/"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"

[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"

[[menu.main]]
    name = "Publications"
    weight = 3
    url  = "/publications/"

[[menu.main]]
    name = "About"
    weight = 4
    url = "/about/"
